<!-- Personality Text Summary -->
<template>
<v-card id="summary" raised>

    <!-- TOOLBAR -->
    <v-toolbar card flat v-if="header">
        <!-- title -->
        <v-toolbar-title>Personality Summary</v-toolbar-title>
        <v-spacer></v-spacer>
        <!-- show / hide information -->
        <v-btn icon>
            <v-icon @click="infoPanel = !infoPanel">info_outline</v-icon>
        </v-btn>
    </v-toolbar>

    <!-- CONTENT -->
    <v-container>
        <!-- information expansion panel -->
        <v-expansion-panel class="info-panel">
            <v-expansion-panel-content v-model="infoPanel">
                <v-card-text class="caption">
                    <p>The personality summary was obtained using <span class="font-weight-bold">IBM Watson's Personality Insights Text Summary.</span> To read more about the text summary generator, check out the <a class="info" href="https://github.com/personality-insights/text-summary" target="_blank">documentation</a>.</p>
                </v-card-text>
            </v-expansion-panel-content>
        </v-expansion-panel>
        <v-card-text>
            <!-- text summary generated by Watson AI -->
            <p v-for="paragraph in paragraphSummary" :key="paragraph">
                {{ paragraph }}
            </p>
        </v-card-text>
    </v-container>
</v-card>
</template>

<script>
export default {
    name: 'PersonalitySummary',
    props: [
        "header",           // show/hide header
        "textSummary"       // text summary created by Watson AI from personality profile
    ],
    data() {
        return {
            infoPanel: false    // show/hide info expansion panel
        }
    },

    computed: {

        // split the text summary into paragraphs to make them more readable
        paragraphSummary() {
            return this.textSummary.split(/\r?\n/);
        }

    }
}
</script>